13.0 rliu mrp sale fields
odoonz/odoonz-addons pull request #28
Opened 2020-07-21 19:39 UTC by RujiaL

2020-07-31 00:04 UTC, gdgellatly requested changes
See request

2020-07-31 00:04 UTC, gdgellatly commented on mrp_sale_fields/models/mrp_production.py
> +        self.sale_id = False
This isn't in the right place.

If production data is returned we are guarenteed to set sale_id, so we only need to take care of the case where there isn't. In any case, this is a compute function and self could be a recordset, so you should assign in a loop to each, and only if no production data.

2020-07-31 00:04 UTC, gdgellatly commented on mrp_sale_fields/models/sale_order.py
> +        self.production_count = False
This basically has the same flaw as the sale_id code.

2020-08-10 06:09 UTC, RujiaL commented on mrp_sale_fields/models/mrp_production.py
> +            production.sale_id = mapped_data.get(production.id, False)
As per discussed, since production_data will be an empty list if it's no data, `if production_data:` condition is removed.

2020-08-10 06:12 UTC, RujiaL commented on mrp_sale_fields/models/sale_order.py
> +            return
Ensure each sale order has 0 in its production_count fields when it doesn't have related manufacture orders since next loop can't set those orders

2020-08-20 22:35 UTC, gdgellatly approved these changes

2020-08-20 22:35 UTC, merged